version: '3.9'

services:
  taxi-online:
    build:
      context: .
      target: development
    environment:
      APP_PORT: ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run dev
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
      - ./node_modules:/app/node_modules
