version: '3.9'

services:
  app:
    build:
      context: .
      target: development
    environment:
      APP_PORT: ${APP_PORT}
      DB_APP_HOST: ${DB_APP_HOST}
      DB_APP_PORT: ${DB_APP_PORT}
      DB_APP_NAME: ${DB_APP_NAME}
      DB_APP_USERNAME: ${DB_APP_USERNAME}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
      - ./node_modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:16-alpine
    ports:
      - ${DB_APP_PORT}:${DB_APP_PORT}
    environment:
      POSTGRES_USER: ${DB_APP_USERNAME}
      POSTGRES_PASSWORD: ${DB_APP_PASSWORD}
      POSTGRES_DB: ${DB_APP_NAME}
      POSTGRES_PORT: ${DB_APP_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${PWD}/docker/db/initdb/:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  node_modules:


networks:
  default:
    driver: bridge
